/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppSpeedRouteImport } from './routes/app.speed'
import { Route as AppSimRouteImport } from './routes/app.sim'
import { Route as AppServicesRouteImport } from './routes/app.services'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppRoamingReportRouteImport } from './routes/app.roaming-report'
import { Route as AppRoamingRouteImport } from './routes/app.roaming'
import { Route as AppRewardRouteImport } from './routes/app.reward'
import { Route as AppReportRouteImport } from './routes/app.report'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPlayRouteImport } from './routes/app.play'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMyBundlesRouteImport } from './routes/app.my-bundles'
import { Route as AppGiftRouteImport } from './routes/app.gift'
import { Route as AppFaydaRouteImport } from './routes/app.fayda'
import { Route as AppFamilyRouteImport } from './routes/app.family'
import { Route as AppDiyRouteImport } from './routes/app.diy'
import { Route as AppBundlesRouteImport } from './routes/app.bundles'
import { Route as AppApnRouteImport } from './routes/app.apn'
import { Route as AppRewardSuccessRouteImport } from './routes/app.reward.success'
import { Route as AppPlayWinRouteImport } from './routes/app.play.win'
import { Route as AppPlayTriviaRouteImport } from './routes/app.play.trivia'
import { Route as AppPlaySpinRouteImport } from './routes/app.play.spin'
import { Route as AppPlayRewardsRouteImport } from './routes/app.play.rewards'
import { Route as AppFamilyCreateRouteImport } from './routes/app.family.create'
import { Route as AppFamilyAddRouteImport } from './routes/app.family.add'
import { Route as AppFamilyMemberIdRouteImport } from './routes/app.family.$memberId'
import { Route as AppFamilyMemberIdBuyRouteImport } from './routes/app.family.$memberId.buy'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeedRoute = AppSpeedRouteImport.update({
  id: '/speed',
  path: '/speed',
  getParentRoute: () => AppRoute,
} as any)
const AppSimRoute = AppSimRouteImport.update({
  id: '/sim',
  path: '/sim',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRoamingReportRoute = AppRoamingReportRouteImport.update({
  id: '/roaming-report',
  path: '/roaming-report',
  getParentRoute: () => AppRoute,
} as any)
const AppRoamingRoute = AppRoamingRouteImport.update({
  id: '/roaming',
  path: '/roaming',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardRoute = AppRewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMyBundlesRoute = AppMyBundlesRouteImport.update({
  id: '/my-bundles',
  path: '/my-bundles',
  getParentRoute: () => AppRoute,
} as any)
const AppGiftRoute = AppGiftRouteImport.update({
  id: '/gift',
  path: '/gift',
  getParentRoute: () => AppRoute,
} as any)
const AppFaydaRoute = AppFaydaRouteImport.update({
  id: '/fayda',
  path: '/fayda',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyRoute = AppFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AppRoute,
} as any)
const AppDiyRoute = AppDiyRouteImport.update({
  id: '/diy',
  path: '/diy',
  getParentRoute: () => AppRoute,
} as any)
const AppBundlesRoute = AppBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AppRoute,
} as any)
const AppApnRoute = AppApnRouteImport.update({
  id: '/apn',
  path: '/apn',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardSuccessRoute = AppRewardSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AppRewardRoute,
} as any)
const AppPlayWinRoute = AppPlayWinRouteImport.update({
  id: '/win',
  path: '/win',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayTriviaRoute = AppPlayTriviaRouteImport.update({
  id: '/trivia',
  path: '/trivia',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlaySpinRoute = AppPlaySpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayRewardsRoute = AppPlayRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppFamilyCreateRoute = AppFamilyCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppFamilyRoute,
} as any)
const AppFamilyAddRoute = AppFamilyAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppFamilyRoute,
} as any)
const AppFamilyMemberIdRoute = AppFamilyMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => AppFamilyRoute,
} as any)
const AppFamilyMemberIdBuyRoute = AppFamilyMemberIdBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => AppFamilyMemberIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/apn': typeof AppApnRoute
  '/app/bundles': typeof AppBundlesRoute
  '/app/diy': typeof AppDiyRoute
  '/app/family': typeof AppFamilyRouteWithChildren
  '/app/fayda': typeof AppFaydaRoute
  '/app/gift': typeof AppGiftRoute
  '/app/my-bundles': typeof AppMyBundlesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/play': typeof AppPlayRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/report': typeof AppReportRoute
  '/app/reward': typeof AppRewardRouteWithChildren
  '/app/roaming': typeof AppRoamingRoute
  '/app/roaming-report': typeof AppRoamingReportRoute
  '/app/search': typeof AppSearchRoute
  '/app/services': typeof AppServicesRoute
  '/app/sim': typeof AppSimRoute
  '/app/speed': typeof AppSpeedRoute
  '/app/support': typeof AppSupportRoute
  '/app/': typeof AppIndexRoute
  '/app/family/$memberId': typeof AppFamilyMemberIdRouteWithChildren
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/create': typeof AppFamilyCreateRoute
  '/app/play/rewards': typeof AppPlayRewardsRoute
  '/app/play/spin': typeof AppPlaySpinRoute
  '/app/play/trivia': typeof AppPlayTriviaRoute
  '/app/play/win': typeof AppPlayWinRoute
  '/app/reward/success': typeof AppRewardSuccessRoute
  '/app/family/$memberId/buy': typeof AppFamilyMemberIdBuyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/apn': typeof AppApnRoute
  '/app/bundles': typeof AppBundlesRoute
  '/app/diy': typeof AppDiyRoute
  '/app/family': typeof AppFamilyRouteWithChildren
  '/app/fayda': typeof AppFaydaRoute
  '/app/gift': typeof AppGiftRoute
  '/app/my-bundles': typeof AppMyBundlesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/play': typeof AppPlayRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/report': typeof AppReportRoute
  '/app/reward': typeof AppRewardRouteWithChildren
  '/app/roaming': typeof AppRoamingRoute
  '/app/roaming-report': typeof AppRoamingReportRoute
  '/app/search': typeof AppSearchRoute
  '/app/services': typeof AppServicesRoute
  '/app/sim': typeof AppSimRoute
  '/app/speed': typeof AppSpeedRoute
  '/app/support': typeof AppSupportRoute
  '/app': typeof AppIndexRoute
  '/app/family/$memberId': typeof AppFamilyMemberIdRouteWithChildren
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/create': typeof AppFamilyCreateRoute
  '/app/play/rewards': typeof AppPlayRewardsRoute
  '/app/play/spin': typeof AppPlaySpinRoute
  '/app/play/trivia': typeof AppPlayTriviaRoute
  '/app/play/win': typeof AppPlayWinRoute
  '/app/reward/success': typeof AppRewardSuccessRoute
  '/app/family/$memberId/buy': typeof AppFamilyMemberIdBuyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/apn': typeof AppApnRoute
  '/app/bundles': typeof AppBundlesRoute
  '/app/diy': typeof AppDiyRoute
  '/app/family': typeof AppFamilyRouteWithChildren
  '/app/fayda': typeof AppFaydaRoute
  '/app/gift': typeof AppGiftRoute
  '/app/my-bundles': typeof AppMyBundlesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/play': typeof AppPlayRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/report': typeof AppReportRoute
  '/app/reward': typeof AppRewardRouteWithChildren
  '/app/roaming': typeof AppRoamingRoute
  '/app/roaming-report': typeof AppRoamingReportRoute
  '/app/search': typeof AppSearchRoute
  '/app/services': typeof AppServicesRoute
  '/app/sim': typeof AppSimRoute
  '/app/speed': typeof AppSpeedRoute
  '/app/support': typeof AppSupportRoute
  '/app/': typeof AppIndexRoute
  '/app/family/$memberId': typeof AppFamilyMemberIdRouteWithChildren
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/create': typeof AppFamilyCreateRoute
  '/app/play/rewards': typeof AppPlayRewardsRoute
  '/app/play/spin': typeof AppPlaySpinRoute
  '/app/play/trivia': typeof AppPlayTriviaRoute
  '/app/play/win': typeof AppPlayWinRoute
  '/app/reward/success': typeof AppRewardSuccessRoute
  '/app/family/$memberId/buy': typeof AppFamilyMemberIdBuyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/apn'
    | '/app/bundles'
    | '/app/diy'
    | '/app/family'
    | '/app/fayda'
    | '/app/gift'
    | '/app/my-bundles'
    | '/app/notifications'
    | '/app/play'
    | '/app/profile'
    | '/app/report'
    | '/app/reward'
    | '/app/roaming'
    | '/app/roaming-report'
    | '/app/search'
    | '/app/services'
    | '/app/sim'
    | '/app/speed'
    | '/app/support'
    | '/app/'
    | '/app/family/$memberId'
    | '/app/family/add'
    | '/app/family/create'
    | '/app/play/rewards'
    | '/app/play/spin'
    | '/app/play/trivia'
    | '/app/play/win'
    | '/app/reward/success'
    | '/app/family/$memberId/buy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/apn'
    | '/app/bundles'
    | '/app/diy'
    | '/app/family'
    | '/app/fayda'
    | '/app/gift'
    | '/app/my-bundles'
    | '/app/notifications'
    | '/app/play'
    | '/app/profile'
    | '/app/report'
    | '/app/reward'
    | '/app/roaming'
    | '/app/roaming-report'
    | '/app/search'
    | '/app/services'
    | '/app/sim'
    | '/app/speed'
    | '/app/support'
    | '/app'
    | '/app/family/$memberId'
    | '/app/family/add'
    | '/app/family/create'
    | '/app/play/rewards'
    | '/app/play/spin'
    | '/app/play/trivia'
    | '/app/play/win'
    | '/app/reward/success'
    | '/app/family/$memberId/buy'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/apn'
    | '/app/bundles'
    | '/app/diy'
    | '/app/family'
    | '/app/fayda'
    | '/app/gift'
    | '/app/my-bundles'
    | '/app/notifications'
    | '/app/play'
    | '/app/profile'
    | '/app/report'
    | '/app/reward'
    | '/app/roaming'
    | '/app/roaming-report'
    | '/app/search'
    | '/app/services'
    | '/app/sim'
    | '/app/speed'
    | '/app/support'
    | '/app/'
    | '/app/family/$memberId'
    | '/app/family/add'
    | '/app/family/create'
    | '/app/play/rewards'
    | '/app/play/spin'
    | '/app/play/trivia'
    | '/app/play/win'
    | '/app/reward/success'
    | '/app/family/$memberId/buy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/speed': {
      id: '/app/speed'
      path: '/speed'
      fullPath: '/app/speed'
      preLoaderRoute: typeof AppSpeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sim': {
      id: '/app/sim'
      path: '/sim'
      fullPath: '/app/sim'
      preLoaderRoute: typeof AppSimRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roaming-report': {
      id: '/app/roaming-report'
      path: '/roaming-report'
      fullPath: '/app/roaming-report'
      preLoaderRoute: typeof AppRoamingReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roaming': {
      id: '/app/roaming'
      path: '/roaming'
      fullPath: '/app/roaming'
      preLoaderRoute: typeof AppRoamingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reward': {
      id: '/app/reward'
      path: '/reward'
      fullPath: '/app/reward'
      preLoaderRoute: typeof AppRewardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/report': {
      id: '/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/play': {
      id: '/app/play'
      path: '/play'
      fullPath: '/app/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-bundles': {
      id: '/app/my-bundles'
      path: '/my-bundles'
      fullPath: '/app/my-bundles'
      preLoaderRoute: typeof AppMyBundlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gift': {
      id: '/app/gift'
      path: '/gift'
      fullPath: '/app/gift'
      preLoaderRoute: typeof AppGiftRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fayda': {
      id: '/app/fayda'
      path: '/fayda'
      fullPath: '/app/fayda'
      preLoaderRoute: typeof AppFaydaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family': {
      id: '/app/family'
      path: '/family'
      fullPath: '/app/family'
      preLoaderRoute: typeof AppFamilyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diy': {
      id: '/app/diy'
      path: '/diy'
      fullPath: '/app/diy'
      preLoaderRoute: typeof AppDiyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bundles': {
      id: '/app/bundles'
      path: '/bundles'
      fullPath: '/app/bundles'
      preLoaderRoute: typeof AppBundlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/apn': {
      id: '/app/apn'
      path: '/apn'
      fullPath: '/app/apn'
      preLoaderRoute: typeof AppApnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reward/success': {
      id: '/app/reward/success'
      path: '/success'
      fullPath: '/app/reward/success'
      preLoaderRoute: typeof AppRewardSuccessRouteImport
      parentRoute: typeof AppRewardRoute
    }
    '/app/play/win': {
      id: '/app/play/win'
      path: '/win'
      fullPath: '/app/play/win'
      preLoaderRoute: typeof AppPlayWinRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/app/play/trivia': {
      id: '/app/play/trivia'
      path: '/trivia'
      fullPath: '/app/play/trivia'
      preLoaderRoute: typeof AppPlayTriviaRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/app/play/spin': {
      id: '/app/play/spin'
      path: '/spin'
      fullPath: '/app/play/spin'
      preLoaderRoute: typeof AppPlaySpinRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/app/play/rewards': {
      id: '/app/play/rewards'
      path: '/rewards'
      fullPath: '/app/play/rewards'
      preLoaderRoute: typeof AppPlayRewardsRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/app/family/create': {
      id: '/app/family/create'
      path: '/create'
      fullPath: '/app/family/create'
      preLoaderRoute: typeof AppFamilyCreateRouteImport
      parentRoute: typeof AppFamilyRoute
    }
    '/app/family/add': {
      id: '/app/family/add'
      path: '/add'
      fullPath: '/app/family/add'
      preLoaderRoute: typeof AppFamilyAddRouteImport
      parentRoute: typeof AppFamilyRoute
    }
    '/app/family/$memberId': {
      id: '/app/family/$memberId'
      path: '/$memberId'
      fullPath: '/app/family/$memberId'
      preLoaderRoute: typeof AppFamilyMemberIdRouteImport
      parentRoute: typeof AppFamilyRoute
    }
    '/app/family/$memberId/buy': {
      id: '/app/family/$memberId/buy'
      path: '/buy'
      fullPath: '/app/family/$memberId/buy'
      preLoaderRoute: typeof AppFamilyMemberIdBuyRouteImport
      parentRoute: typeof AppFamilyMemberIdRoute
    }
  }
}

interface AppFamilyMemberIdRouteChildren {
  AppFamilyMemberIdBuyRoute: typeof AppFamilyMemberIdBuyRoute
}

const AppFamilyMemberIdRouteChildren: AppFamilyMemberIdRouteChildren = {
  AppFamilyMemberIdBuyRoute: AppFamilyMemberIdBuyRoute,
}

const AppFamilyMemberIdRouteWithChildren =
  AppFamilyMemberIdRoute._addFileChildren(AppFamilyMemberIdRouteChildren)

interface AppFamilyRouteChildren {
  AppFamilyMemberIdRoute: typeof AppFamilyMemberIdRouteWithChildren
  AppFamilyAddRoute: typeof AppFamilyAddRoute
  AppFamilyCreateRoute: typeof AppFamilyCreateRoute
}

const AppFamilyRouteChildren: AppFamilyRouteChildren = {
  AppFamilyMemberIdRoute: AppFamilyMemberIdRouteWithChildren,
  AppFamilyAddRoute: AppFamilyAddRoute,
  AppFamilyCreateRoute: AppFamilyCreateRoute,
}

const AppFamilyRouteWithChildren = AppFamilyRoute._addFileChildren(
  AppFamilyRouteChildren,
)

interface AppPlayRouteChildren {
  AppPlayRewardsRoute: typeof AppPlayRewardsRoute
  AppPlaySpinRoute: typeof AppPlaySpinRoute
  AppPlayTriviaRoute: typeof AppPlayTriviaRoute
  AppPlayWinRoute: typeof AppPlayWinRoute
}

const AppPlayRouteChildren: AppPlayRouteChildren = {
  AppPlayRewardsRoute: AppPlayRewardsRoute,
  AppPlaySpinRoute: AppPlaySpinRoute,
  AppPlayTriviaRoute: AppPlayTriviaRoute,
  AppPlayWinRoute: AppPlayWinRoute,
}

const AppPlayRouteWithChildren =
  AppPlayRoute._addFileChildren(AppPlayRouteChildren)

interface AppRewardRouteChildren {
  AppRewardSuccessRoute: typeof AppRewardSuccessRoute
}

const AppRewardRouteChildren: AppRewardRouteChildren = {
  AppRewardSuccessRoute: AppRewardSuccessRoute,
}

const AppRewardRouteWithChildren = AppRewardRoute._addFileChildren(
  AppRewardRouteChildren,
)

interface AppRouteChildren {
  AppApnRoute: typeof AppApnRoute
  AppBundlesRoute: typeof AppBundlesRoute
  AppDiyRoute: typeof AppDiyRoute
  AppFamilyRoute: typeof AppFamilyRouteWithChildren
  AppFaydaRoute: typeof AppFaydaRoute
  AppGiftRoute: typeof AppGiftRoute
  AppMyBundlesRoute: typeof AppMyBundlesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPlayRoute: typeof AppPlayRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppReportRoute: typeof AppReportRoute
  AppRewardRoute: typeof AppRewardRouteWithChildren
  AppRoamingRoute: typeof AppRoamingRoute
  AppRoamingReportRoute: typeof AppRoamingReportRoute
  AppSearchRoute: typeof AppSearchRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSimRoute: typeof AppSimRoute
  AppSpeedRoute: typeof AppSpeedRoute
  AppSupportRoute: typeof AppSupportRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApnRoute: AppApnRoute,
  AppBundlesRoute: AppBundlesRoute,
  AppDiyRoute: AppDiyRoute,
  AppFamilyRoute: AppFamilyRouteWithChildren,
  AppFaydaRoute: AppFaydaRoute,
  AppGiftRoute: AppGiftRoute,
  AppMyBundlesRoute: AppMyBundlesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPlayRoute: AppPlayRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppReportRoute: AppReportRoute,
  AppRewardRoute: AppRewardRouteWithChildren,
  AppRoamingRoute: AppRoamingRoute,
  AppRoamingReportRoute: AppRoamingReportRoute,
  AppSearchRoute: AppSearchRoute,
  AppServicesRoute: AppServicesRoute,
  AppSimRoute: AppSimRoute,
  AppSpeedRoute: AppSpeedRoute,
  AppSupportRoute: AppSupportRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
